# Generated by Django 5.2.13 on 2026-05-26 04:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CookieAdminSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "csv_export_delimiter",
                    models.CharField(
                        choices=[
                            (",", "Запятая (,)"),
                            (";", "Точка с запятой (;)"),
                            ("\t", "Табуляция (TAB)"),
                            ("|", "Вертикальная черта (|)"),
                        ],
                        default=",",
                        max_length=8,
                        verbose_name="Разделитель CSV-экспорта",
                    ),
                ),
                (
                    "show_empty_category_block_override",
                    models.BooleanField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Override: show empty category block",
                    ),
                ),
                (
                    "show_customize_action_without_optional_override",
                    models.BooleanField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name=(
                            "Override: show customize action without optional categories"
                        ),
                    ),
                ),
                (
                    "empty_category_block_text_override",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Override: empty category block text",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Настройки админ-инструментов cookie",
                "verbose_name_plural": "Настройки админ-инструментов cookie",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="CookieBannerTextPreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=32, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("launcher_label", models.CharField(max_length=128)),
                ("eyebrow_text", models.CharField(max_length=128)),
                ("title_text", models.TextField()),
                ("description_text", models.TextField()),
                ("reconsent_notice_text", models.TextField()),
                ("reask_notice_text", models.TextField()),
                ("accept_all_label", models.CharField(max_length=128)),
                ("reject_label", models.CharField(max_length=128)),
                ("required_only_label", models.CharField(max_length=128)),
                ("customize_label", models.CharField(max_length=128)),
                ("custom_section_summary", models.CharField(max_length=128)),
                ("required_section_title", models.CharField(max_length=128)),
                ("required_section_empty_text", models.CharField(max_length=255)),
                ("optional_section_title", models.CharField(max_length=128)),
                ("optional_section_empty_text", models.CharField(max_length=255)),
                ("save_custom_label", models.CharField(max_length=128)),
                ("preferences_link_label", models.CharField(max_length=128)),
                ("dismiss_label", models.CharField(max_length=128)),
                ("noscript_text", models.CharField(max_length=255)),
                ("noscript_link_label", models.CharField(max_length=128)),
                ("is_box_template", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Текстовая заготовка cookie-баннера",
                "verbose_name_plural": "Текстовые заготовки cookie-баннера",
                "ordering": ["code", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CookieCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=64, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_required", models.BooleanField(default=False)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Cookie-категория",
                "verbose_name_plural": "Cookie-категории",
                "ordering": ["sort_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="CookiePolicyTextPreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=32, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("content_text", models.TextField()),
                ("is_box_template", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Текстовая заготовка политики cookie",
                "verbose_name_plural": "Текстовые заготовки политики cookie",
                "ordering": ["code", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CookieBannerRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1, unique=True)),
                (
                    "launcher_label",
                    models.CharField(default="Настройки cookie", max_length=128),
                ),
                (
                    "eyebrow_text",
                    models.CharField(default="Настройки cookie", max_length=128),
                ),
                (
                    "title_text",
                    models.TextField(
                        default="Мы используем cookie для работы сайта и настройки дополнительных категорий."
                    ),
                ),
                (
                    "description_text",
                    models.TextField(
                        default="Обязательные категории включены всегда. Необязательные категории можно разрешить сразу, оставить выключенными или выбрать вручную."
                    ),
                ),
                (
                    "reconsent_notice_text",
                    models.TextField(
                        default="Доступна новая редакция cookie-policy. Обновите свой выбор категорий."
                    ),
                ),
                (
                    "reask_notice_text",
                    models.TextField(
                        default="Мы периодически уточняем выбор cookie-категорий. Подтвердите или обновите настройки."
                    ),
                ),
                (
                    "accept_all_label",
                    models.CharField(default="Принять все", max_length=128),
                ),
                (
                    "reject_label",
                    models.CharField(
                        default="Отказаться от необязательных cookie",
                        max_length=128,
                        verbose_name="Надпись кнопки отказа",
                    ),
                ),
                (
                    "required_only_label",
                    models.CharField(
                        default="Только необходимые cookie", max_length=128
                    ),
                ),
                (
                    "customize_label",
                    models.CharField(default="Выбрать категории", max_length=128),
                ),
                (
                    "custom_section_summary",
                    models.CharField(
                        default="Собственный выбор категорий", max_length=128
                    ),
                ),
                (
                    "required_section_title",
                    models.CharField(default="Обязательные категории", max_length=128),
                ),
                (
                    "required_section_empty_text",
                    models.CharField(
                        default="Нет обязательных категорий.", max_length=255
                    ),
                ),
                (
                    "optional_section_title",
                    models.CharField(
                        default="Необязательные категории", max_length=128
                    ),
                ),
                (
                    "optional_section_empty_text",
                    models.CharField(
                        default="Сейчас нет дополнительных категорий для выбора.",
                        max_length=255,
                    ),
                ),
                (
                    "save_custom_label",
                    models.CharField(default="Сохранить выбор", max_length=128),
                ),
                (
                    "preferences_link_label",
                    models.CharField(
                        default="Полная страница настроек", max_length=128
                    ),
                ),
                ("dismiss_label", models.CharField(default="Свернуть", max_length=128)),
                (
                    "close_tooltip_text",
                    models.CharField(
                        default="Закрыть баннер cookie",
                        max_length=128,
                        verbose_name="Подсказка кнопки закрытия",
                    ),
                ),
                (
                    "close_aria_label",
                    models.CharField(
                        default="Закрыть баннер cookie",
                        max_length=128,
                        verbose_name="ARIA-метка кнопки закрытия",
                    ),
                ),
                (
                    "noscript_text",
                    models.CharField(
                        default="Если JavaScript отключён, можно открыть",
                        max_length=255,
                    ),
                ),
                (
                    "noscript_link_label",
                    models.CharField(
                        default="страницу настроек cookie", max_length=128
                    ),
                ),
                (
                    "banner_variant",
                    models.CharField(
                        choices=[
                            ("bar", "Плашка"),
                            ("card", "Карточка"),
                            ("modal", "Модальное окно"),
                        ],
                        default="card",
                        max_length=32,
                    ),
                ),
                (
                    "consent_ui_variant",
                    models.CharField(
                        choices=[("inline", "Встроенный"), ("panel", "Панель")],
                        default="panel",
                        max_length=32,
                    ),
                ),
                (
                    "reconsent_notice_variant",
                    models.CharField(
                        choices=[("inline", "Встроенный"), ("alert", "Оповещение")],
                        default="inline",
                        max_length=32,
                    ),
                ),
                (
                    "mobile_banner_variant",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bar", "Плашка"),
                            ("card", "Карточка"),
                            ("modal", "Модальное окно"),
                        ],
                        default="",
                        max_length=32,
                    ),
                ),
                (
                    "mobile_consent_ui_variant",
                    models.CharField(
                        blank=True,
                        choices=[("inline", "Встроенный"), ("panel", "Панель")],
                        default="",
                        max_length=32,
                    ),
                ),
                (
                    "mobile_reconsent_notice_variant",
                    models.CharField(
                        blank=True,
                        choices=[("inline", "Встроенный"), ("alert", "Оповещение")],
                        default="",
                        max_length=32,
                    ),
                ),
                (
                    "text_preset_code",
                    models.CharField(default="ru_balanced", max_length=32),
                ),
                (
                    "mobile_text_preset_code",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "layout_variant",
                    models.CharField(
                        choices=[("compact", "Компактный"), ("wide", "Широкий")],
                        default="compact",
                        max_length=32,
                    ),
                ),
                (
                    "theme_variant",
                    models.CharField(
                        choices=[("light", "Светлый"), ("contrast", "Контрастный")],
                        default="light",
                        max_length=32,
                    ),
                ),
                (
                    "desktop_position",
                    models.CharField(
                        choices=[
                            ("bottom_right", "Снизу справа"),
                            ("bottom_left", "Снизу слева"),
                            ("center", "По центру экрана"),
                            ("bottom_fullwidth", "Снизу на всю ширину"),
                        ],
                        default="bottom_right",
                        max_length=32,
                    ),
                ),
                (
                    "mobile_position",
                    models.CharField(
                        choices=[
                            ("bottom", "Снизу"),
                            ("top", "Сверху"),
                            ("center", "По центру экрана"),
                            ("bottom_fullwidth", "Снизу на всю ширину"),
                        ],
                        default="bottom",
                        max_length=32,
                    ),
                ),
                (
                    "color_preset",
                    models.CharField(
                        choices=[
                            ("light", "Светлый"),
                            ("contrast", "Контрастный"),
                            ("custom", "Пользовательские цвета"),
                        ],
                        default="light",
                        max_length=32,
                        verbose_name="Цветовая заготовка",
                    ),
                ),
                (
                    "custom_bg_color",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "custom_text_color",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "custom_primary_color",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "custom_primary_text_color",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "custom_border_color",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "custom_surface_color",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "custom_overlay_color",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                ("panel_padding_px", models.PositiveIntegerField(default=20)),
                ("section_gap_px", models.PositiveIntegerField(default=14)),
                ("button_gap_px", models.PositiveIntegerField(default=10)),
                ("overlay_opacity", models.PositiveIntegerField(default=55)),
                (
                    "show_media_slot",
                    models.BooleanField(
                        default=False, verbose_name="Показывать медиаблок"
                    ),
                ),
                (
                    "media_slot_type",
                    models.CharField(
                        choices=[("icon", "Иконка"), ("image", "Изображение")],
                        default="icon",
                        max_length=16,
                        verbose_name="Тип медиаблока",
                    ),
                ),
                (
                    "media_icon_emoji",
                    models.CharField(
                        blank=True,
                        default="🍪",
                        max_length=8,
                        verbose_name="Эмодзи для медиаблока",
                    ),
                ),
                (
                    "media_image_url",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="URL изображения для медиаблока",
                    ),
                ),
                (
                    "media_image_alt",
                    models.CharField(
                        blank=True,
                        default="Иконка cookie",
                        max_length=128,
                        verbose_name="Альтернативный текст изображения медиаблока",
                    ),
                ),
                (
                    "show_close_control",
                    models.BooleanField(
                        default=True, verbose_name="Показывать кнопку закрытия"
                    ),
                ),
                (
                    "close_control_placement",
                    models.CharField(
                        choices=[("left", "Слева"), ("right", "Справа")],
                        default="right",
                        max_length=16,
                        verbose_name="Расположение кнопки закрытия",
                    ),
                ),
                (
                    "mobile_close_control_placement",
                    models.CharField(
                        blank=True,
                        choices=[("left", "Слева"), ("right", "Справа")],
                        default="",
                        max_length=16,
                        verbose_name="Переопределение расположения кнопки закрытия для мобильной версии",
                    ),
                ),
                (
                    "show_reject_action",
                    models.BooleanField(
                        default=False, verbose_name="Показывать кнопку отказа"
                    ),
                ),
                (
                    "mobile_show_close_control",
                    models.BooleanField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Переопределение показа кнопки закрытия для мобильной версии",
                    ),
                ),
                (
                    "mobile_show_reject_action",
                    models.BooleanField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Переопределение показа кнопки отказа для мобильной версии",
                    ),
                ),
                (
                    "blocking_mode_until_choice",
                    models.BooleanField(
                        default=False,
                        help_text="Блокировать взаимодействие со страницей, пока пользователь явно не выберет настройки cookie.",
                        verbose_name="Блокирующий режим до выбора",
                    ),
                ),
                (
                    "mobile_blocking_mode_until_choice",
                    models.BooleanField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Переопределение блокирующего режима для мобильной версии",
                    ),
                ),
                (
                    "hide_launcher_after_decision",
                    models.BooleanField(
                        default=False,
                        verbose_name="Скрывать кнопку настроек после выбора",
                    ),
                ),
                (
                    "mobile_hide_launcher_after_decision",
                    models.BooleanField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Переопределение скрытия кнопки настроек для мобильной версии",
                    ),
                ),
                (
                    "keep_visible_after_accept_all",
                    models.BooleanField(
                        default=False,
                        verbose_name="Оставлять баннер видимым после действия «принять все»",
                    ),
                ),
                (
                    "keep_visible_after_required_only",
                    models.BooleanField(
                        default=False,
                        verbose_name="Оставлять баннер видимым после действия «только обязательные»",
                    ),
                ),
                (
                    "keep_visible_after_save_custom",
                    models.BooleanField(
                        default=False,
                        verbose_name="Оставлять баннер видимым после действия «сохранить выбранные категории»",
                    ),
                ),
                (
                    "mobile_keep_visible_after_accept_all",
                    models.BooleanField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Переопределение видимости баннера после «принять все» для мобильной версии",
                    ),
                ),
                (
                    "mobile_keep_visible_after_required_only",
                    models.BooleanField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Переопределение видимости баннера после «только обязательные» для мобильной версии",
                    ),
                ),
                (
                    "mobile_keep_visible_after_save_custom",
                    models.BooleanField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Переопределение видимости баннера после «сохранить выбранные категории» для мобильной версии",
                    ),
                ),
                (
                    "hide_for_bots_override",
                    models.BooleanField(
                        blank=True,
                        default=None,
                        help_text="Переопределение скрытия для ботов во время выполнения: пусто — использовать значение из настроек, включено — скрывать баннер для определённых ботов, выключено — показывать баннер.",
                        null=True,
                        verbose_name="Переопределение скрытия для ботов",
                    ),
                ),
                ("is_box_template", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cloned_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cloned_banner_revisions",
                        to="django_cookies_152fz.cookiebannerrevision",
                        verbose_name="Скопировано из редакции",
                    ),
                ),
            ],
            options={
                "verbose_name": "Редакция cookie-баннера",
                "verbose_name_plural": "Редакции cookie-баннера",
                "ordering": ["-published_at", "-version", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CookiePolicyRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1, unique=True)),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("plain_text", "Обычный текст"),
                            ("markdown", "Разметка Markdown"),
                            ("html", "Разметка HTML"),
                            ("pdf_file", "PDF-файл"),
                        ],
                        default="plain_text",
                        max_length=32,
                    ),
                ),
                ("content_text", models.TextField(blank=True)),
                (
                    "content_file",
                    models.FileField(
                        blank=True, upload_to="django_cookies_152fz/policies/"
                    ),
                ),
                ("categories_snapshot", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("is_box_template", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cloned_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cloned_revisions",
                        to="django_cookies_152fz.cookiepolicyrevision",
                        verbose_name="Скопировано из редакции",
                    ),
                ),
            ],
            options={
                "verbose_name": "Редакция cookie-policy",
                "verbose_name_plural": "Редакции cookie-policy",
                "ordering": ["-published_at", "-version", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CookieConsentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anonymous_token", models.CharField(blank=True, max_length=128)),
                ("selected_categories", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[("current", "Актуальная"), ("outdated", "Устаревшая")],
                        default="current",
                        max_length=32,
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=64)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("locale", models.CharField(blank=True, max_length=32)),
                ("request_id", models.CharField(blank=True, max_length=128)),
                ("session_key_hash", models.CharField(blank=True, max_length=128)),
                ("extra_meta", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cookie_consent_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "policy_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="records",
                        to="django_cookies_152fz.cookiepolicyrevision",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись cookie-согласия",
                "verbose_name_plural": "Записи cookie-согласий",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CookieRegistryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=64, unique=True)),
                ("provider", models.CharField(max_length=255)),
                ("purpose", models.TextField()),
                ("retention", models.CharField(blank=True, max_length=255)),
                ("cookie_names", models.JSONField(blank=True, default=list)),
                ("src_url", models.CharField(blank=True, max_length=500)),
                (
                    "clear_strategy",
                    models.CharField(
                        choices=[
                            ("none", "Нет"),
                            ("best_effort_delete", "Удалить по возможности"),
                            ("adapter_hook", "Хук адаптера"),
                        ],
                        default="none",
                        max_length=32,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registry_items",
                        to="django_cookies_152fz.cookiecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Элемент cookie-реестра",
                "verbose_name_plural": "Элементы cookie-реестра",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="CookiePolicyRevisionRegistryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registry_code", models.CharField(max_length=64)),
                ("category_code", models.CharField(max_length=64)),
                ("provider", models.CharField(max_length=255)),
                ("purpose", models.TextField()),
                ("retention", models.CharField(blank=True, max_length=255)),
                ("cookie_names", models.JSONField(blank=True, default=list)),
                ("src_url", models.CharField(blank=True, max_length=500)),
                (
                    "clear_strategy",
                    models.CharField(
                        choices=[
                            ("none", "Нет"),
                            ("best_effort_delete", "Удалить по возможности"),
                            ("adapter_hook", "Хук адаптера"),
                        ],
                        default="none",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "policy_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registry_items",
                        to="django_cookies_152fz.cookiepolicyrevision",
                    ),
                ),
                (
                    "registry_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revision_snapshots",
                        to="django_cookies_152fz.cookieregistryitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Элемент реестра редакции cookie-policy",
                "verbose_name_plural": "Элементы реестра редакции cookie-policy",
                "ordering": ["category_code", "registry_code", "id"],
            },
        ),
        migrations.CreateModel(
            name="CookieBannerState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "anonymous_token",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("dismissed_at", models.DateTimeField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "decision_action",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("accept_all", "Принять все"),
                            ("reject_all", "Отклонить все"),
                            ("required_only", "Только обязательные"),
                            ("save_custom", "Сохранить выбранные категории"),
                        ],
                        max_length=32,
                        verbose_name="Действие выбора",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cookie_banner_state",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Состояние cookie-баннера",
                "verbose_name_plural": "Состояния cookie-баннера",
                "ordering": ["-updated_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["updated_at"], name="cookie_banner_updated_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="cookie_banner_created_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("user__isnull", False),
                            ("anonymous_token__isnull", False),
                            _connector="OR",
                        ),
                        name="cookie_banner_state_has_subject",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("anonymous_token__isnull", False)),
                        fields=("anonymous_token",),
                        name="cookie_banner_state_unique_anonymous_token",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CookieConsentEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("accepted", "Принято"),
                            ("updated", "Обновлено"),
                            ("outdated", "Устарело"),
                        ],
                        max_length=32,
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=64)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("locale", models.CharField(blank=True, max_length=32)),
                ("request_id", models.CharField(blank=True, max_length=128)),
                ("session_key_hash", models.CharField(blank=True, max_length=128)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("extra_meta", models.JSONField(blank=True, default=dict)),
                (
                    "occurred_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cookie_consent_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="django_cookies_152fz.cookieconsentrecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "Событие cookie-согласия",
                "verbose_name_plural": "События cookie-согласий",
                "ordering": ["occurred_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["occurred_at"], name="cookie_evt_occurred_idx"
                    ),
                    models.Index(
                        fields=["event_type", "occurred_at"],
                        name="cookie_evt_type_occurred_idx",
                    ),
                    models.Index(fields=["created_at"], name="cookie_evt_created_idx"),
                    models.Index(
                        fields=["cookie_consent_record", "occurred_at"],
                        name="cookie_evt_record_occurred_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="cookieconsentrecord",
            index=models.Index(
                fields=["status", "created_at"], name="cookie_rec_status_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cookieconsentrecord",
            index=models.Index(
                fields=["anonymous_token", "created_at"],
                name="cookie_rec_token_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cookieconsentrecord",
            index=models.Index(
                fields=["user", "created_at"], name="cookie_rec_user_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cookieconsentrecord",
            index=models.Index(
                fields=["policy_revision", "created_at"],
                name="cookie_rec_policy_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cookieconsentrecord",
            index=models.Index(fields=["updated_at"], name="cookie_rec_updated_idx"),
        ),
        migrations.AddConstraint(
            model_name="cookieconsentrecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "current"), ("user__isnull", False)),
                fields=("user",),
                name="cookie_rec_current_user_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="cookieconsentrecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("anonymous_token__gt", ""),
                    ("status", "current"),
                    ("user__isnull", True),
                ),
                fields=("anonymous_token",),
                name="cookie_rec_current_token_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="cookiepolicyrevisionregistryitem",
            constraint=models.UniqueConstraint(
                fields=("policy_revision", "registry_item"),
                name="cookie_policy_revision_registry_item_unique_link",
            ),
        ),
    ]
