"""Canonical string constants of the package.

This module serves two purposes:
1. it avoids scattering "magic strings" across the code by key;
2. it fixes a public vocabulary of values that models, services,
   configuration checks, tests and the API can safely rely on.

Although some values are only used in later roadmap stages (e.g. verified
consents, access policies, cookie-flow), it is convenient to keep them in one
place from the project scaffold onward. This lowers the risk that the same
business entity ends up named differently across layers.
"""

# Identifier of the provider's main package.
APP_LABEL = "django_consent_152fz"
PROVIDER_CODE = "ru_152fz"
API_APP = "django_consent_152fz.api"

# Names of top-level settings Django settings.
SETTING_USE_API = "USE_API_152FZ"
SETTING_CONFIG = "DJANGO_CONSENT_152FZ"
SETTING_CONFIG_LEGACY = "DJANGO_152FZ_CONSENT"
SETTING_API_PREFIX = "API_152FZ_URL_PREFIX"
SETTING_API_SAFE_ROOT_STUBS_ENABLED = "API_152FZ_SAFE_ROOT_STUBS_ENABLED"
SETTING_API_INCLUDE_SCHEMA = "API_152FZ_INCLUDE_SCHEMA"
SETTING_API_AUTH_CLASSES = "API_152FZ_AUTHENTICATION_CLASSES"
SETTING_API_PERMISSION_CLASSES = "API_152FZ_PERMISSION_CLASSES"
SETTING_PUBLIC_API_ENABLED = "PUBLIC_API_152FZ_ENABLED"
SETTING_PUBLIC_API_PREFIX = "PUBLIC_API_152FZ_URL_PREFIX"
SETTING_PUBLIC_API_ALLOWED_PURPOSES = "PUBLIC_API_152FZ_ALLOWED_PURPOSES"
SETTING_PUBLIC_API_SHOW_ROOT = "PUBLIC_API_152FZ_SHOW_ROOT"
SETTING_PUBLIC_API_THROTTLE_ENABLED = "PUBLIC_API_152FZ_THROTTLE_ENABLED"
SETTING_PUBLIC_API_THROTTLE_IP_RATE = "PUBLIC_API_152FZ_THROTTLE_IP_RATE"
SETTING_PUBLIC_API_THROTTLE_ANON_RATE = "PUBLIC_API_152FZ_THROTTLE_ANON_RATE"
SETTING_PUBLIC_API_THROTTLE_IP_WRITE_FLOOR_RATE = (
    "PUBLIC_API_152FZ_THROTTLE_IP_WRITE_FLOOR_RATE"
)
SETTING_TRUSTED_PROXY_IPS = "TRUSTED_PROXY_152FZ_IPS"
SETTING_TRUSTED_PROXY_HOPS = "TRUSTED_PROXY_152FZ_HOPS"
SETTING_ANON_TOKEN_TTL_SECONDS = "ANONYMOUS_TOKEN_152FZ_TTL_SECONDS"
SETTING_ANON_TOKEN_REVOKE_ON_ATTACH = "ANONYMOUS_TOKEN_152FZ_REVOKE_ON_ATTACH"
SETTING_PUBLIC_STATUS_FAIL_LIMIT = "PUBLIC_API_152FZ_STATUS_FAIL_LIMIT"
SETTING_PUBLIC_STATUS_FAIL_WINDOW_SECONDS = (
    "PUBLIC_API_152FZ_STATUS_FAIL_WINDOW_SECONDS"
)

# Feature flags of the package. They are forced to turn on and turn off modules without
# branching the code on the integrator's side.
CONFIG_ENABLE_CORE = "enable_core"
CONFIG_ENABLE_VERIFIED_CONSENTS = "enable_verified_consents"
CONFIG_ENABLE_ACCESS_POLICIES = "enable_access_policies"
CONFIG_SAMPLE_DOCUMENTS = "sample_documents"
CONFIG_SAMPLE_DOCUMENTS_LOAD_MODE = "load_mode"
CONFIG_DOCUMENT_TEMPLATES = "document_templates"
CONFIG_DOCUMENT_TEMPLATES_DEFAULT_TEXT_FORMAT = "default_text_format"
CONFIG_DOCUMENT_TEMPLATES_ADMIN_EDITOR_MODE = "admin_editor_mode"
CONFIG_DOCUMENT_TEMPLATES_ADMIN_WYSIWYG_WIDGET = "admin_wysiwyg_widget"
CONFIG_DOCUMENT_TEMPLATES_ADMIN_WYSIWYG_WIDGET_ATTRS = "admin_wysiwyg_widget_attrs"
CONFIG_DOCUMENT_TEMPLATES_HTML_TO_PDF_HOOK = "html_to_pdf_hook"
CONFIG_SUBJECT_CONSENTS = "subject_consents"
CONFIG_SUBJECT_CONSENTS_OPEN_MODE = "open_mode"
CONFIG_SUBJECT_CONSENTS_ALLOW_ANONYMOUS_WITHDRAW = "allow_anonymous_withdraw"
CONFIG_SUBJECT_CONSENTS_INPUT_MODE = "consent_input_mode"
CONFIG_SUBJECT_CONSENTS_CHECKBOX_REQUIRED = "checkbox_required"
CONFIG_SUBJECT_CONSENTS_DECLINE_ACTION = "decline_action"
CONFIG_SUBJECT_CONSENTS_DECLINE_WARNING_ENABLED = "decline_warning_enabled"
CONFIG_SUBJECT_CONSENTS_DECLINE_WARNING_TEXT = "decline_warning_text"
CONFIG_ADMIN_NAVIGATION = "admin_navigation"
CONFIG_ADMIN_NAVIGATION_ENABLED = "enabled"
CONFIG_ADMIN_NAVIGATION_APP_ORDER = "app_order"
CONFIG_ADMIN_NAVIGATION_COLLAPSED_APPS = "collapsed_apps"
CONFIG_ADMIN_NAVIGATION_CONSENT_APPS = "consent_apps"
CONFIG_ADMIN_NAVIGATION_SECTION_TITLE = "section_title"

# Names of the optional application for setting up the cookie module.
VERIFIED_CONSENTS_APP = "django_consent_152fz.verified_consents"

# Load mode of the boxed document samples. The values deliberately remain
# In English as part of a public machine-readable settings contract.
SAMPLE_DOCUMENTS_LOAD_MODE_DISABLED = "disabled"
SAMPLE_DOCUMENTS_LOAD_MODE_COMMAND = "command"
SAMPLE_DOCUMENTS_LOAD_MODE_AUTO = "auto"
SAMPLE_DOCUMENTS_LOAD_MODES = (
    SAMPLE_DOCUMENTS_LOAD_MODE_DISABLED,
    SAMPLE_DOCUMENTS_LOAD_MODE_COMMAND,
    SAMPLE_DOCUMENTS_LOAD_MODE_AUTO,
)

DOCUMENT_TEMPLATES_DEFAULT_TEXT_FORMAT_PLAIN = "plain_text"
DOCUMENT_TEMPLATES_DEFAULT_TEXT_FORMAT_MARKDOWN = "markdown"
DOCUMENT_TEMPLATES_DEFAULT_TEXT_FORMAT_HTML = "html"
DOCUMENT_TEMPLATES_DEFAULT_TEXT_FORMATS = (
    DOCUMENT_TEMPLATES_DEFAULT_TEXT_FORMAT_PLAIN,
    DOCUMENT_TEMPLATES_DEFAULT_TEXT_FORMAT_MARKDOWN,
    DOCUMENT_TEMPLATES_DEFAULT_TEXT_FORMAT_HTML,
)

DOCUMENT_TEMPLATES_EDITOR_MODE_TEXTAREA = "textarea"
DOCUMENT_TEMPLATES_EDITOR_MODE_WYSIWYG = "wysiwyg"
DOCUMENT_TEMPLATES_EDITOR_MODES = (
    DOCUMENT_TEMPLATES_EDITOR_MODE_TEXTAREA,
    DOCUMENT_TEMPLATES_EDITOR_MODE_WYSIWYG,
)

# Response strategies on consent withdrawal.
# They are based on the feedback of the post-processing hooks of the following stages.
WITHDRAW_STRATEGY_BLOCK = "block"
WITHDRAW_STRATEGY_DELETE = "delete"
WITHDRAW_STRATEGIES = (
    WITHDRAW_STRATEGY_BLOCK,
    WITHDRAW_STRATEGY_DELETE,
)

# Regime of universal consent. They determine the fact of obsolescence,
# How the system should react to an outdated consent.
RECONSENT_MODE_SOFT = "soft_reconsent"
RECONSENT_MODE_HARD = "hard_reconsent"
RECONSENT_MODES = (
    RECONSENT_MODE_SOFT,
    RECONSENT_MODE_HARD,
)

# Signing frequency policies within one thread purpose + document.
CONSENT_FREQUENCY_ONCE_UNTIL_OUTDATED = "once_until_outdated"
CONSENT_FREQUENCY_EVERY_TIME = "every_time"
CONSENT_FREQUENCIES = (
    CONSENT_FREQUENCY_ONCE_UNTIL_OUTDATED,
    CONSENT_FREQUENCY_EVERY_TIME,
)

# Availability of consent script by subject type.
SUBJECT_AVAILABILITY_AUTHENTICATED_ONLY = "authenticated_only"
SUBJECT_AVAILABILITY_AUTHENTICATED_AND_ANONYMOUS = "authenticated_and_anonymous"
SUBJECT_AVAILABILITIES = (
    SUBJECT_AVAILABILITY_AUTHENTICATED_ONLY,
    SUBJECT_AVAILABILITY_AUTHENTICATED_AND_ANONYMOUS,
)

# Reasons for requiring a signature in a transport/API/template contract.
CONSENT_REQUIRED_REASON_NOT_REQUIRED = "not_required"
CONSENT_REQUIRED_REASON_EVERY_TIME = "every_time"
CONSENT_REQUIRED_REASON_OUTDATED = "outdated"
CONSENT_REQUIRED_REASON_MISSING_OR_OTHER = "missing_or_other"
CONSENT_REQUIRED_REASON_NOT_APPLICABLE = "not_applicable"
CONSENT_REQUIRED_REASONS = (
    CONSENT_REQUIRED_REASON_NOT_REQUIRED,
    CONSENT_REQUIRED_REASON_EVERY_TIME,
    CONSENT_REQUIRED_REASON_OUTDATED,
    CONSENT_REQUIRED_REASON_MISSING_OR_OTHER,
    CONSENT_REQUIRED_REASON_NOT_APPLICABLE,
)

# Machine-readable verified-transition states for the web -> paper scenario.
VERIFIED_TRANSITION_STATUS_PAPER_REQUIRED = "paper_required"
VERIFIED_TRANSITION_STATUS_AWAITING_UPLOAD = "awaiting_upload"
VERIFIED_TRANSITION_STATUS_PENDING_VERIFICATION = "pending_verification"
VERIFIED_TRANSITION_STATUS_VERIFIED = "verified"
VERIFIED_TRANSITION_STATUS_REJECTED = "rejected"
VERIFIED_TRANSITION_STATUSES = (
    VERIFIED_TRANSITION_STATUS_PAPER_REQUIRED,
    VERIFIED_TRANSITION_STATUS_AWAITING_UPLOAD,
    VERIFIED_TRANSITION_STATUS_PENDING_VERIFICATION,
    VERIFIED_TRANSITION_STATUS_VERIFIED,
    VERIFIED_TRANSITION_STATUS_REJECTED,
)

# Consent status.
CONSENT_STATUS_CURRENT = "current"
CONSENT_STATUS_OUTDATED = "outdated"
CONSENT_STATUS_WITHDRAWN = "withdrawn"
CONSENT_STATUS_PENDING_CONFIRMATION = "pending_confirmation"
CONSENT_STATUS_REJECTED = "rejected"
CONSENT_STATUS_DELETED = "deleted"
CONSENT_STATUSES = (
    CONSENT_STATUS_CURRENT,
    CONSENT_STATUS_OUTDATED,
    CONSENT_STATUS_WITHDRAWN,
    CONSENT_STATUS_PENDING_CONFIRMATION,
    CONSENT_STATUS_REJECTED,
    CONSENT_STATUS_DELETED,
)

# Confirmation method of consent. This matters for the audit:
# One "consent has been received" may have a different legal nature.
CONFIRMATION_METHOD_WEB_CHECKBOX = "web_checkbox"
CONFIRMATION_METHOD_WEB_BUTTON = "web_button"
CONFIRMATION_METHOD_API_ACCEPT = "api_accept"
CONFIRMATION_METHOD_UPLOADED_PAPER = "uploaded_paper"
CONFIRMATION_METHOD_ADMIN_CONFIRMED = "admin_confirmed"
CONFIRMATION_METHOD_EMPLOYEE_CONFIRMED = "employee_confirmed"
CONFIRMATION_METHODS = (
    CONFIRMATION_METHOD_WEB_CHECKBOX,
    CONFIRMATION_METHOD_WEB_BUTTON,
    CONFIRMATION_METHOD_API_ACCEPT,
    CONFIRMATION_METHOD_UPLOADED_PAPER,
    CONFIRMATION_METHOD_ADMIN_CONFIRMED,
    CONFIRMATION_METHOD_EMPLOYEE_CONFIRMED,
)

# Types of events in the consent-flow audit.
CONSENT_EVENT_GIVEN = "given"
CONSENT_EVENT_WITHDRAWN = "withdrawn"
CONSENT_EVENT_OUTDATED = "outdated"
CONSENT_EVENT_RECONFIRMED = "reconfirmed"
CONSENT_EVENT_ADMIN_CONFIRMED = "admin_confirmed"
CONSENT_EVENT_EMPLOYEE_CONFIRMED = "employee_confirmed"
CONSENT_EVENT_PAPER_UPLOADED = "paper_uploaded"
CONSENT_EVENT_REJECTED = "rejected"
CONSENT_EVENT_BLOCKED = "blocked"
CONSENT_EVENT_DELETE_REQUESTED = "delete_requested"
CONSENT_EVENT_ANONYMIZED = "anonymized"
CONSENT_EVENT_TYPES = (
    CONSENT_EVENT_GIVEN,
    CONSENT_EVENT_WITHDRAWN,
    CONSENT_EVENT_OUTDATED,
    CONSENT_EVENT_RECONFIRMED,
    CONSENT_EVENT_ADMIN_CONFIRMED,
    CONSENT_EVENT_EMPLOYEE_CONFIRMED,
    CONSENT_EVENT_PAPER_UPLOADED,
    CONSENT_EVENT_REJECTED,
    CONSENT_EVENT_BLOCKED,
    CONSENT_EVENT_DELETE_REQUESTED,
    CONSENT_EVENT_ANONYMIZED,
)

# Roles of actors performing actions in the event log.
CONSENT_ACTOR_SUBJECT = "subject"
CONSENT_ACTOR_EMPLOYEE = "employee"
CONSENT_ACTOR_ADMIN = "admin"
CONSENT_ACTOR_SYSTEM = "system"
CONSENT_ACTOR_TYPES = (
    CONSENT_ACTOR_SUBJECT,
    CONSENT_ACTOR_EMPLOYEE,
    CONSENT_ACTOR_ADMIN,
    CONSENT_ACTOR_SYSTEM,
)

# Audience-scope models for access rules and document rollout.
AUDIENCE_SCOPE_ALL_REGISTERED_USERS = "all_registered_users"
AUDIENCE_SCOPE_DJANGO_GROUP = "django_group"
AUDIENCE_SCOPE_ANONYMOUS_SUBJECTS = "anonymous_subjects"
AUDIENCE_SCOPES = (
    AUDIENCE_SCOPE_ALL_REGISTERED_USERS,
    AUDIENCE_SCOPE_DJANGO_GROUP,
    AUDIENCE_SCOPE_ANONYMOUS_SUBJECTS,
)

# Ways to assign the person responsible for personal data.
PDM_SCOPE_GLOBAL = "global"
PDM_SCOPE_DJANGO_GROUPS = "django_groups"
PDM_SCOPES = (
    PDM_SCOPE_GLOBAL,
    PDM_SCOPE_DJANGO_GROUPS,
)

# Access policies: what to do when consent is missing or outdated.
ACCESS_POLICY_ACTION_DENY = "deny"
ACCESS_POLICY_ACTION_READ_ONLY = "read_only"
ACCESS_POLICY_ACTION_REDIRECT_TO_CONSENT = "redirect_to_consent"
ACCESS_POLICY_ACTION_RESPECT_RECONSENT_MODE = "respect_reconsent_mode"
ACCESS_POLICY_MISSING_CONSENT_ACTIONS = (
    ACCESS_POLICY_ACTION_DENY,
    ACCESS_POLICY_ACTION_READ_ONLY,
    ACCESS_POLICY_ACTION_REDIRECT_TO_CONSENT,
)
ACCESS_POLICY_OUTDATED_CONSENT_ACTIONS = (
    ACCESS_POLICY_ACTION_RESPECT_RECONSENT_MODE,
    ACCESS_POLICY_ACTION_DENY,
    ACCESS_POLICY_ACTION_READ_ONLY,
    ACCESS_POLICY_ACTION_REDIRECT_TO_CONSENT,
)

# Normalized results of access policy calculation.
# These are no longer individual checks, but the final access decision.
ACCESS_POLICY_RESOLUTION_ALLOW = "allow"
ACCESS_POLICY_RESOLUTION_DENY = "deny"
ACCESS_POLICY_RESOLUTION_READ_ONLY = "read_only"
ACCESS_POLICY_RESOLUTION_REDIRECT_TO_CONSENT = "redirect_to_consent"
ACCESS_POLICY_RESOLUTIONS = (
    ACCESS_POLICY_RESOLUTION_ALLOW,
    ACCESS_POLICY_RESOLUTION_DENY,
    ACCESS_POLICY_RESOLUTION_READ_ONLY,
    ACCESS_POLICY_RESOLUTION_REDIRECT_TO_CONSENT,
)


# Canonical self-service contract for opening consent documents from subject UI.
SUBJECT_CONSENTS_OPEN_MODE_PAGE = "page"
SUBJECT_CONSENTS_OPEN_MODE_NEW_WINDOW = "new_window"
SUBJECT_CONSENTS_OPEN_MODE_MODAL = "modal"
SUBJECT_CONSENTS_OPEN_MODES = (
    SUBJECT_CONSENTS_OPEN_MODE_PAGE,
    SUBJECT_CONSENTS_OPEN_MODE_NEW_WINDOW,
    SUBJECT_CONSENTS_OPEN_MODE_MODAL,
)
SUBJECT_CONSENTS_INPUT_MODE_CHECKBOX = "checkbox"
SUBJECT_CONSENTS_INPUT_MODE_RADIO = "radio"
SUBJECT_CONSENTS_INPUT_MODES = (
    SUBJECT_CONSENTS_INPUT_MODE_CHECKBOX,
    SUBJECT_CONSENTS_INPUT_MODE_RADIO,
)
SUBJECT_CONSENTS_DECLINE_ACTION_BLOCK_SUBMIT = "block_submit"
SUBJECT_CONSENTS_DECLINE_ACTION_ALLOW_SUBMIT = "allow_submit"
SUBJECT_CONSENTS_DECLINE_ACTIONS = (
    SUBJECT_CONSENTS_DECLINE_ACTION_BLOCK_SUBMIT,
    SUBJECT_CONSENTS_DECLINE_ACTION_ALLOW_SUBMIT,
)
