# Generated by Django 5.2.13 on 2026-05-26 04:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsentAccessPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=64, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("resource_code", models.CharField(max_length=128)),
                ("app_label", models.CharField(blank=True, max_length=64)),
                ("model_name", models.CharField(blank=True, max_length=64)),
                ("action", models.CharField(max_length=64)),
                (
                    "on_missing_consent",
                    models.CharField(
                        choices=[
                            ("deny", "Deny"),
                            ("read_only", "Read only"),
                            ("redirect_to_consent", "Redirect to consent"),
                        ],
                        default="deny",
                        max_length=32,
                    ),
                ),
                (
                    "on_outdated_consent",
                    models.CharField(
                        choices=[
                            (
                                "respect_reconsent_mode",
                                "Учитывать режим повторного согласия",
                            ),
                            ("deny", "Deny"),
                            ("read_only", "Read only"),
                            ("redirect_to_consent", "Redirect to consent"),
                        ],
                        default="respect_reconsent_mode",
                        max_length=32,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("extra_meta", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Consent Access Policy",
                "verbose_name_plural": "Consent Access Policies",
                "ordering": ["resource_code", "action", "code"],
            },
        ),
        migrations.CreateModel(
            name="ConsentAudienceRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope_mode",
                    models.CharField(
                        choices=[
                            ("all_registered_users", "All registered users"),
                            ("django_group", "Django group"),
                            ("anonymous_subjects", "Anonymous subjects"),
                        ],
                        max_length=32,
                    ),
                ),
                ("is_required", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Consent Audience Rule",
                "verbose_name_plural": "Consent Audience Rules",
                "ordering": ["purpose__code", "document__code", "scope_mode", "id"],
            },
        ),
        migrations.CreateModel(
            name="ConsentEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("given", "Given"),
                            ("withdrawn", "Withdrawn"),
                            ("outdated", "Outdated"),
                            ("reconfirmed", "Reconfirmed"),
                            ("admin_confirmed", "Admin confirmed"),
                            ("employee_confirmed", "Employee confirmed"),
                            ("paper_uploaded", "Paper uploaded"),
                            ("rejected", "Rejected"),
                            ("blocked", "Blocked"),
                            ("delete_requested", "Delete requested"),
                            ("anonymized", "Anonymized"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "actor_type",
                    models.CharField(
                        choices=[
                            ("subject", "Subject"),
                            ("employee", "Employee"),
                            ("admin", "Admin"),
                            ("system", "System"),
                        ],
                        default="system",
                        max_length=32,
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=64)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("locale", models.CharField(blank=True, max_length=32)),
                ("request_id", models.CharField(blank=True, max_length=128)),
                ("session_key_hash", models.CharField(blank=True, max_length=128)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("extra_meta", models.JSONField(blank=True, default=dict)),
                (
                    "occurred_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Consent Event",
                "verbose_name_plural": "Consent Events",
                "ordering": ["occurred_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="ConsentPurpose",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=64, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("fields_config", models.JSONField(default=list)),
                (
                    "withdraw_strategy",
                    models.CharField(
                        choices=[("block", "Block"), ("delete", "Delete")],
                        default="block",
                        max_length=32,
                    ),
                ),
                (
                    "reconsent_mode",
                    models.CharField(
                        choices=[
                            ("soft_reconsent", "Мягкое повторное согласие"),
                            ("hard_reconsent", "Жёсткое повторное согласие"),
                        ],
                        default="soft_reconsent",
                        max_length=32,
                    ),
                ),
                (
                    "consent_frequency_policy",
                    models.CharField(
                        choices=[
                            ("once_until_outdated", "Один раз до новой редакции"),
                            ("every_time", "Подписывать при каждом действии"),
                        ],
                        default="once_until_outdated",
                        max_length=32,
                    ),
                ),
                (
                    "subject_availability_policy",
                    models.CharField(
                        choices=[
                            (
                                "authenticated_only",
                                "Только авторизованные пользователи",
                            ),
                            (
                                "authenticated_and_anonymous",
                                "Авторизованные и анонимные пользователи",
                            ),
                        ],
                        default="authenticated_and_anonymous",
                        max_length=48,
                    ),
                ),
                (
                    "consent_input_mode_override",
                    models.CharField(
                        choices=[
                            ("inherit", "Наследовать глобальную настройку"),
                            ("checkbox", "Подтверждение флажком"),
                            ("radio", "Выбор «согласен/не согласен»"),
                        ],
                        default="inherit",
                        max_length=32,
                    ),
                ),
                (
                    "checkbox_required_override",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "decline_action_override",
                    models.CharField(
                        choices=[
                            ("inherit", "Наследовать глобальную настройку"),
                            ("block_submit", "Блокировать отправку"),
                            ("allow_submit", "Разрешать отправку"),
                        ],
                        default="inherit",
                        max_length=32,
                    ),
                ),
                (
                    "decline_warning_enabled_override",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "decline_warning_text_override",
                    models.CharField(blank=True, max_length=255),
                ),
                ("is_experimental", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Consent Purpose",
                "verbose_name_plural": "Consent Purposes",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ConsentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_ref", models.CharField(blank=True, max_length=128)),
                ("anonymous_token", models.CharField(blank=True, max_length=128)),
                ("fields_snapshot", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("current", "Current"),
                            ("outdated", "Outdated"),
                            ("withdrawn", "Withdrawn"),
                            ("pending_confirmation", "Pending confirmation"),
                            ("rejected", "Rejected"),
                            ("deleted", "Deleted"),
                        ],
                        default="current",
                        max_length=32,
                    ),
                ),
                (
                    "confirmation_method",
                    models.CharField(
                        choices=[
                            ("web_checkbox", "Web checkbox"),
                            ("web_button", "Web button"),
                            ("api_accept", "API accept"),
                            ("uploaded_paper", "Uploaded paper"),
                            ("admin_confirmed", "Admin confirmed"),
                            ("employee_confirmed", "Employee confirmed"),
                        ],
                        default="web_checkbox",
                        max_length=32,
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=64)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("locale", models.CharField(blank=True, max_length=32)),
                ("extra_meta", models.JSONField(blank=True, default=dict)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("confirmation_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Consent Record",
                "verbose_name_plural": "Consent Records",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConsentSelfServiceSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject_consents_open_mode",
                    models.CharField(
                        choices=[
                            ("page", "Open on page"),
                            ("new_window", "Open in new window"),
                            ("modal", "Open in modal dialog"),
                        ],
                        default="page",
                        max_length=32,
                        verbose_name="Режим открытия документа",
                    ),
                ),
                (
                    "subject_consents_list_mode",
                    models.CharField(
                        choices=[
                            ("all", "Все"),
                            ("pending_only", "Только на подпись"),
                            ("signed_only", "Только подписанные"),
                        ],
                        default="all",
                        max_length=32,
                        verbose_name="Режим списка согласий",
                    ),
                ),
                (
                    "consent_input_mode",
                    models.CharField(
                        choices=[
                            ("checkbox", "Checkbox confirmation"),
                            ("radio", "Radio agree or decline"),
                        ],
                        default="checkbox",
                        max_length=32,
                        verbose_name="Режим подтверждения согласия",
                    ),
                ),
                (
                    "checkbox_required",
                    models.BooleanField(
                        default=True, verbose_name="Обязательный флажок"
                    ),
                ),
                (
                    "decline_action",
                    models.CharField(
                        choices=[
                            ("block_submit", "Block submit"),
                            ("allow_submit", "Allow submit"),
                        ],
                        default="block_submit",
                        max_length=32,
                        verbose_name="Поведение при отказе",
                    ),
                ),
                (
                    "decline_warning_enabled",
                    models.BooleanField(
                        default=True,
                        verbose_name="Показывать предупреждение при отказе",
                    ),
                ),
                (
                    "decline_warning_text",
                    models.CharField(
                        default="Если вы не согласны на обработку персональных данных, мы не сможем связаться с вами по заявке.",
                        max_length=255,
                        verbose_name="Текст предупреждения при отказе",
                    ),
                ),
                (
                    "csv_export_delimiter",
                    models.CharField(
                        choices=[
                            (",", "Запятая (,)"),
                            (";", "Точка с запятой (;)"),
                            ("\t", "Табуляция (TAB)"),
                            ("|", "Вертикальная черта (|)"),
                        ],
                        default=",",
                        max_length=8,
                        verbose_name="Разделитель CSV-экспорта",
                    ),
                ),
                (
                    "printable_pdf_paper_size",
                    models.CharField(
                        choices=[
                            ("a4", "A4 (210×297 мм)"),
                            ("a5", "A5 (148×210 мм)"),
                            ("letter", "Letter (8,5×11 дюйма)"),
                        ],
                        default="a4",
                        max_length=16,
                        verbose_name="Формат бумаги для печатного PDF",
                    ),
                ),
                (
                    "printable_pdf_font_family",
                    models.CharField(
                        choices=[
                            ("times_new_roman", "Times New Roman"),
                            ("arial", "Arial"),
                        ],
                        default="times_new_roman",
                        max_length=32,
                        verbose_name="Шрифт печатного PDF",
                    ),
                ),
                (
                    "printable_pdf_font_size",
                    models.PositiveSmallIntegerField(
                        default=12, verbose_name="Размер шрифта печатного PDF"
                    ),
                ),
                (
                    "printable_pdf_text_align",
                    models.CharField(
                        choices=[
                            ("left", "По левому краю"),
                            ("center", "По центру"),
                            ("right", "По правому краю"),
                            ("justify", "По ширине"),
                        ],
                        default="left",
                        max_length=16,
                        verbose_name="Выравнивание текста печатного PDF",
                    ),
                ),
                (
                    "printable_pdf_show_signature_footer",
                    models.BooleanField(
                        default=True, verbose_name="Добавлять блок подписи внизу PDF"
                    ),
                ),
                (
                    "printable_pdf_signature_align",
                    models.CharField(
                        choices=[
                            ("left", "Слева"),
                            ("center", "По центру"),
                            ("right", "Справа"),
                        ],
                        default="center",
                        max_length=16,
                        verbose_name="Выравнивание подписи (ПОДПИСЬ/ФИО)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
            ],
            options={
                "verbose_name": "Consent Self-service Settings",
                "verbose_name_plural": "Consent Self-service Settings",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="DocumentRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purpose_code", models.CharField(max_length=64)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("plain_text", "Plain text"),
                            ("markdown", "Markdown"),
                            ("html", "HTML"),
                            ("pdf_file", "PDF file"),
                            ("office_file", "Office file (DOC/DOCX/ODT/ODTX)"),
                        ],
                        default="plain_text",
                        max_length=32,
                    ),
                ),
                ("content_text", models.TextField(blank=True)),
                (
                    "content_file",
                    models.FileField(
                        blank=True, upload_to="django_consent_152fz/documents/"
                    ),
                ),
                ("fields_snapshot", models.JSONField(default=list)),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("is_box_template", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Document Revision",
                "verbose_name_plural": "Document Revisions",
                "ordering": ["document_id", "purpose_code", "-version"],
            },
        ),
        migrations.CreateModel(
            name="LegalDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=64, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("document_type", models.CharField(default="consent", max_length=64)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Legal Document",
                "verbose_name_plural": "Legal Documents",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ModuleOperationAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("operation_code", models.CharField(max_length=128)),
                ("source", models.CharField(blank=True, max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("dry_run", "Dry run"),
                            ("error", "Error"),
                        ],
                        default="success",
                        max_length=16,
                    ),
                ),
                ("target_model", models.CharField(blank=True, max_length=128)),
                ("target_id", models.CharField(blank=True, max_length=128)),
                ("summary", models.TextField(blank=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("result", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Журнал операций модуля",
                "verbose_name_plural": "Журналы операций модуля",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PersonalDataManagerAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope_mode",
                    models.CharField(
                        choices=[
                            ("global", "Глобально"),
                            ("django_groups", "По Django-группам"),
                        ],
                        default="global",
                        max_length=32,
                    ),
                ),
                ("can_manage_purposes", models.BooleanField(default=False)),
                ("can_manage_documents", models.BooleanField(default=False)),
                ("can_publish_revisions", models.BooleanField(default=False)),
                ("can_manage_audience_rules", models.BooleanField(default=False)),
                ("can_manage_access_policies", models.BooleanField(default=False)),
                ("can_handle_verified_consents", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Personal Data Manager Assignment",
                "verbose_name_plural": "Personal Data Manager Assignments",
                "ordering": ["user_id"],
            },
        ),
        migrations.CreateModel(
            name="RevokedAnonymousToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("revoked_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-revoked_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="consentaudiencerule",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_consent_audience_rules",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="consentaudiencerule",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consent_audience_rules",
                to="auth.group",
            ),
        ),
        migrations.AddField(
            model_name="consentevent",
            name="actor_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="consent_events_actor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="consentaudiencerule",
            name="purpose",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audience_rules",
                to="django_consent_152fz.consentpurpose",
            ),
        ),
        migrations.AddField(
            model_name="consentaccesspolicy",
            name="purpose",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="access_policies",
                to="django_consent_152fz.consentpurpose",
            ),
        ),
        migrations.AddField(
            model_name="consentrecord",
            name="confirmed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="confirmed_consent_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="consentrecord",
            name="purpose",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="consent_records",
                to="django_consent_152fz.consentpurpose",
            ),
        ),
        migrations.AddField(
            model_name="consentrecord",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="consent_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="consentevent",
            name="consent_record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="django_consent_152fz.consentrecord",
            ),
        ),
        migrations.AddField(
            model_name="consentrecord",
            name="document_revision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="consent_records",
                to="django_consent_152fz.documentrevision",
            ),
        ),
        migrations.AddField(
            model_name="documentrevision",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="revisions",
                to="django_consent_152fz.legaldocument",
            ),
        ),
        migrations.AddField(
            model_name="consentaudiencerule",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audience_rules",
                to="django_consent_152fz.legaldocument",
            ),
        ),
        migrations.AddField(
            model_name="consentaccesspolicy",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="access_policies",
                to="django_consent_152fz.legaldocument",
            ),
        ),
        migrations.AddField(
            model_name="moduleoperationauditlog",
            name="actor_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="module_operation_audit_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="ConsentModuleOperationAuditLog",
            fields=[],
            options={
                "verbose_name": "Журнал операций согласий 152-ФЗ",
                "verbose_name_plural": "Журналы операций согласий 152-ФЗ",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("django_consent_152fz.moduleoperationauditlog",),
        ),
        migrations.AddField(
            model_name="personaldatamanagerassignment",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="personal_data_manager_assignments",
                to="auth.group",
            ),
        ),
        migrations.AddField(
            model_name="personaldatamanagerassignment",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personal_data_manager_assignment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="consentrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("user__isnull", False),
                    models.Q(("anonymous_token", ""), _negated=True),
                    _connector="OR",
                ),
                name="ck_consent_record_subject_present",
            ),
        ),
        migrations.AddConstraint(
            model_name="consentrecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "current"), ("user__isnull", False)),
                fields=("user", "purpose", "document_revision"),
                name="uq_consent_record_current_auth_subject_stream",
            ),
        ),
        migrations.AddConstraint(
            model_name="consentrecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status", "current"),
                    ("user__isnull", True),
                    models.Q(("anonymous_token", ""), _negated=True),
                ),
                fields=("anonymous_token", "purpose", "document_revision"),
                name="uq_consent_record_current_anon_subject_stream",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentrevision",
            constraint=models.UniqueConstraint(
                fields=("document", "purpose_code", "version"),
                name="uq_doc_revision_document_purpose_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="consentaccesspolicy",
            constraint=models.UniqueConstraint(
                fields=("resource_code", "action"),
                name="uq_access_policy_resource_action",
            ),
        ),
        migrations.AddIndex(
            model_name="moduleoperationauditlog",
            index=models.Index(
                fields=["operation_code", "created_at"],
                name="django_cons_operati_8d0c3a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="moduleoperationauditlog",
            index=models.Index(
                fields=["source", "created_at"], name="django_cons_source_eaf7d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="moduleoperationauditlog",
            index=models.Index(
                fields=["status", "created_at"], name="django_cons_status_99ae47_idx"
            ),
        ),
    ]
