# Generated by Django 5.2.13 on 2026-05-26 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import django_consent_152fz.verified_consents.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("django_consent_152fz", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VerifiedConsentPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verification_mode",
                    models.CharField(
                        choices=[
                            ("web_only", "Web only"),
                            ("paper_required", "Paper required"),
                            ("goskey_required", "Goskey required"),
                            ("paper_or_goskey", "Paper or Goskey"),
                        ],
                        default="paper_required",
                        max_length=32,
                    ),
                ),
                (
                    "flow_scope",
                    models.CharField(
                        choices=[
                            ("both", "Both (self-service and forms)"),
                            ("self_service_only", "Self-service only"),
                            ("forms_only", "Forms only"),
                        ],
                        default="both",
                        max_length=32,
                    ),
                ),
                (
                    "legacy_web_consent_policy",
                    models.CharField(
                        choices=[
                            (
                                "keep_web_current",
                                "Keep existing web consent as current",
                            ),
                            (
                                "mark_web_outdated",
                                "Mark existing web consent as outdated",
                            ),
                            (
                                "withdraw_web_now",
                                "Withdraw existing web consent immediately",
                            ),
                            (
                                "withdraw_after_paper_confirmed",
                                "Withdraw existing web consent after paper is confirmed",
                            ),
                        ],
                        default="mark_web_outdated",
                        max_length=32,
                    ),
                ),
                ("allow_subject_self_upload", models.BooleanField(default=True)),
                ("allow_draft_data_before_upload", models.BooleanField(default=True)),
                (
                    "pre_upload_access_mode",
                    models.CharField(
                        choices=[
                            ("block", "Block"),
                            ("allow_limited", "Allow limited access"),
                        ],
                        default="block",
                        max_length=32,
                    ),
                ),
                (
                    "notification_mode",
                    models.CharField(
                        choices=[
                            ("audit_only", "Audit log only"),
                            ("assignment_users", "Notify responsible users"),
                        ],
                        default="audit_only",
                        max_length=32,
                    ),
                ),
                ("notification_templates", models.JSONField(blank=True, default=dict)),
                ("notify_on_data_saved", models.BooleanField(default=False)),
                ("notify_on_paper_uploaded", models.BooleanField(default=True)),
                ("notify_on_verified", models.BooleanField(default=True)),
                ("notify_on_rejected", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("extra_meta", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="verified_policies",
                        to="django_consent_152fz.legaldocument",
                    ),
                ),
                (
                    "purpose",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="verified_policies",
                        to="django_consent_152fz.consentpurpose",
                    ),
                ),
            ],
            options={
                "verbose_name": "Verified Consent Policy",
                "verbose_name_plural": "Verified Consent Policies",
                "ordering": ["purpose__code", "document__code", "id"],
            },
        ),
        migrations.CreateModel(
            name="VerifiedConsentArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "artifact_type",
                    models.CharField(
                        choices=[
                            ("paper_document", "Paper document"),
                            ("external_signature", "External signature"),
                        ],
                        default="paper_document",
                        max_length=32,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        upload_to=django_consent_152fz.verified_consents.models._verified_artifact_upload_to,
                    ),
                ),
                ("subject_signed_at", models.DateTimeField(blank=True, null=True)),
                ("external_provider", models.CharField(blank=True, max_length=64)),
                ("external_ref", models.CharField(blank=True, max_length=128)),
                ("note", models.TextField(blank=True)),
                ("extra_meta", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "consent_record",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="verified_artifact",
                        to="django_consent_152fz.consentrecord",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="artifacts",
                        to="verified_consents.verifiedconsentpolicy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Verified Consent Artifact",
                "verbose_name_plural": "Verified Consent Artifacts",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="VerifiedConsentSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anonymous_token", models.CharField(blank=True, max_length=128)),
                ("subject_ref", models.CharField(blank=True, max_length=255)),
                ("form_code", models.CharField(blank=True, max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft_data", "Draft data"),
                            ("awaiting_paper_upload", "Awaiting paper upload"),
                            ("paper_uploaded", "Paper uploaded"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft_data",
                        max_length=32,
                    ),
                ),
                ("subject_data", models.JSONField(blank=True, default=dict)),
                (
                    "generated_blank_file",
                    models.FileField(
                        blank=True, upload_to="django_consent_152fz/verified_blanks/"
                    ),
                ),
                ("blank_generated_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("extra_meta", models.JSONField(blank=True, default=dict)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "consent_record",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_submission",
                        to="django_consent_152fz.consentrecord",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="verified_submissions",
                        to="django_consent_152fz.legaldocument",
                    ),
                ),
                (
                    "latest_artifact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submissions",
                        to="verified_consents.verifiedconsentartifact",
                    ),
                ),
                (
                    "purpose",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="verified_submissions",
                        to="django_consent_152fz.consentpurpose",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_consent_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Verified Consent Submission",
                "verbose_name_plural": "Verified Consent Submissions",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="VerifiedConsentFormPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("form_code", models.CharField(max_length=128)),
                (
                    "verification_mode_override",
                    models.CharField(
                        choices=[
                            ("inherit", "Inherit from purpose/document policy"),
                            ("web_only", "Web only"),
                            ("paper_required", "Paper required"),
                            ("goskey_required", "Goskey required"),
                            ("paper_or_goskey", "Paper or Goskey"),
                        ],
                        default="inherit",
                        max_length=32,
                    ),
                ),
                (
                    "draft_data_policy_override",
                    models.CharField(
                        choices=[
                            ("inherit", "Inherit from purpose/document policy"),
                            ("allow", "Allow draft data before upload"),
                            ("forbid", "Forbid draft data before upload"),
                        ],
                        default="inherit",
                        max_length=32,
                    ),
                ),
                (
                    "pre_upload_access_mode_override",
                    models.CharField(
                        choices=[
                            ("inherit", "Inherit from purpose/document policy"),
                            ("block", "Block"),
                            ("allow_limited", "Allow limited access"),
                        ],
                        default="inherit",
                        max_length=32,
                    ),
                ),
                (
                    "notification_mode_override",
                    models.CharField(
                        choices=[
                            ("inherit", "Inherit from purpose/document policy"),
                            ("audit_only", "Audit log only"),
                            ("assignment_users", "Notify responsible users"),
                        ],
                        default="inherit",
                        max_length=32,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("extra_meta", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="verified_form_policies",
                        to="django_consent_152fz.legaldocument",
                    ),
                ),
                (
                    "purpose",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="verified_form_policies",
                        to="django_consent_152fz.consentpurpose",
                    ),
                ),
            ],
            options={
                "verbose_name": "Verified Consent Form Policy",
                "verbose_name_plural": "Verified Consent Form Policies",
                "ordering": ["form_code", "purpose__code", "document__code", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("purpose", "document", "form_code"),
                        name="uq_verified_form_policy_purpose_document_form",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="verifiedconsentpolicy",
            constraint=models.UniqueConstraint(
                fields=("purpose", "document"),
                name="uq_verified_policy_purpose_document",
            ),
        ),
        migrations.AddIndex(
            model_name="verifiedconsentsubmission",
            index=models.Index(
                fields=["purpose", "document", "status"],
                name="verified_co_purpose_64fa0f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="verifiedconsentsubmission",
            index=models.Index(
                fields=["user", "status"], name="verified_co_user_id_274f9a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="verifiedconsentsubmission",
            index=models.Index(
                fields=["anonymous_token", "status"],
                name="verified_co_anonymo_16fe71_idx",
            ),
        ),
    ]
